#!/usr/bin/bash
if command -v mypy
then
	echo "Typechecking (mypy) Lexer"
	mypy lexer.py
	echo "Typechecking (mypy) Parser"
	mypy parser.py
	echo "Typechecking (mypy) Typechecker"
	mypy typechecker.py
	echo "Typechecking (mypy) Evaluator"
	mypy evaluator.py
else
	echo "mypy not found, skipping python typechecks."
fi
echo Testing Lexer
python -m unittest test_lexer.py
echo "(lexer)"
echo ==========
echo Testing Parser
python -m unittest test_parser.py
echo "(parser)"
echo ==========
echo Testing Typechecker
python -m unittest test_typechecker.py
echo "(typechecker)"
echo ==========
echo Testing Evaluator
python -m unittest test_evaluator.py
echo "(evaluator)"
